### ISSUE TITLE
Registry.slashMember should accept secret not idcommitment

### ISSUE THREAD

**Issue by AtHeartEngineer** [Rate-Limiting-Nullifier/rlnjs#50]
`registry1().slashMember(poseidon1([status1.secret]))`

@mhchia @curryrasul `registry.slashMember()` should accept the secret as an input right? Not the `idCommitment`? 

This doesn't matter as far as the "security" of the protocol, because the registry is just keeping track of who is registered and who has been slashed, but as a matter of enforcing how the concept works and making sure the correct `idcommitments` are being slashed, the `secret` should be the input right?

Then maybe we can add another method called `slashMemberByCommitment()` to make it more explicit?

**Comment by mhchia** [comment]
Agreed on both. `slashMember(input)` looks like input should be something that can slash the member, and in our case, it's the secret
